import logging
from typing import Dict, Any

logger = logging.getLogger("AgentConductor")

class DataSchemaValidator:
    """
    Validates and normalizes non-deterministic AI payloads into rigid schemas 
    acceptable by transactional systems and enterprise databases.
    """
    def normalize_llm_json(self, raw_llm_dict: Dict[str, Any]) -> Dict[str, Any]:
        logger.info("Normalizing JSON strings into strict UiPath argument data types.")
        
        # Clean currency variants generated by unstable LLM configurations
        raw_amount = raw_llm_dict.get("amount", "0")
        if isinstance(raw_amount, str):
            clean_amount = float(raw_amount.replace("$", "").replace(",", "").strip())
        else:
            clean_amount = float(raw_amount)

        normalized = {
            "vendor_name": str(raw_llm_dict.get("vendor", "Unknown Vendor")).strip().upper(),
            "total_amount": clean_amount,
            "requires_human_verification": False
        }
        
        if clean_amount <= 0:
            normalized["requires_human_verification"] = True
            
        return normalized
